version: '3.7'
services: 
  mongo:
    image: mongo:4
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
  zookeeper:
    image: wurstmeister/zookeeper:latest
    tmpfs: /datalog
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_PORT: 9092
  kafka-hq:
    image: tchiotludo/akhq:0.16.0
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9092"
    ports:
      - 9090:8080
    depends_on:
      - kafka

volumes:
  mongo_data: 
 