version: '3.7'
services: 
  mongo:
    image: mongo:4
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    depends_on:
      - zookeeper
    ports:
      - 9002:9002
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

volumes:
  mongo_data: 
