module.exports = {
  projects: [
    '<rootDir>/apps/web/caas',
    '<rootDir>/apps/srv/artifact-service',
    '<rootDir>/apps/srv/test-suite-service',
    '<rootDir>/apps/srv/certification-service',
    '<rootDir>/apps/srv/job-executor-service',
    '<rootDir>/apps/srv/test-orchestrator-service',
    '<rootDir>/libs/web/artifact-runner',
    '<rootDir>/libs/web/confirmance-test',
    '<rootDir>/libs/web/certificate-issuer',
    '<rootDir>/libs/web/auth',
    '<rootDir>/libs/web/test-environment',
    '<rootDir>/libs/web/api',
    '<rootDir>/libs/srv/auth',
    '<rootDir>/libs/srv/config',
    '<rootDir>/libs/srv/mongo',
    '<rootDir>/libs/srv/kafka',
  ],
};
